/* ═══════════════════════════════════════════════════════════════════
   Auto-generated by scripts/fetch-intel.mjs on a 6-hour schedule.
   Do not hand-edit — changes are overwritten on the next run.
   Placeholder until the first scheduled run.
   ═══════════════════════════════════════════════════════════════════ */
const TIP_AUTOFEED = [];
