/* ═══════════════════════════════════════════════════════════════════
   TIP — Wires each content type's schema/prompt/sanitizer/output name
   into one config both scripts/fetch-intel.mjs and lambda/fetch-intel
   iterate over, so neither has to hand-roll the per-type plumbing.
   ═══════════════════════════════════════════════════════════════════ */

import { fetchContent } from './fetchContent.mjs';
import {
  FEED_SCHEMA, sanitizeFeedItem, stableFeedId,
  HYPOTHESIS_SCHEMA, sanitizeHypothesis, stableHypothesisId,
  ADVERSARY_SCHEMA, sanitizeAdversary, stableAdversaryId,
  DARKWEB_SCHEMA, sanitizeDarkwebItem, stableDarkwebId,
} from './schemas.mjs';
import {
  FEED_SYSTEM_PROMPT, HYPOTHESIS_SYSTEM_PROMPT, ADVERSARY_SYSTEM_PROMPT, DARKWEB_SYSTEM_PROMPT,
} from './prompts.mjs';

export const CONTENT_TYPES = [
  {
    key: 'feed',
    label: 'feed',
    schema: FEED_SCHEMA,
    systemPrompt: FEED_SYSTEM_PROMPT,
    userPrompt: 'Research and report the most significant ongoing cyber threats right now.',
    sanitize: sanitizeFeedItem,
    stableId: stableFeedId,
    globalVar: 'TIP_AUTOFEED',
    fileName: 'autofeed.js',
  },
  {
    key: 'hypothesis',
    label: 'hunt-lab',
    schema: HYPOTHESIS_SCHEMA,
    systemPrompt: HYPOTHESIS_SYSTEM_PROMPT,
    userPrompt: 'Research recent real attack campaigns and produce hunting hypotheses for them.',
    sanitize: sanitizeHypothesis,
    stableId: stableHypothesisId,
    globalVar: 'TIP_AUTOFEED_HUNTLAB',
    fileName: 'autofeed-huntlab.js',
  },
  {
    key: 'adversary',
    label: 'adversary',
    schema: ADVERSARY_SCHEMA,
    systemPrompt: ADVERSARY_SYSTEM_PROMPT,
    userPrompt: 'Research threat actors with real, recently reported activity or attribution.',
    sanitize: sanitizeAdversary,
    stableId: stableAdversaryId,
    globalVar: 'TIP_AUTOFEED_ADVERSARY',
    fileName: 'autofeed-adversary.js',
  },
  {
    key: 'darkweb',
    label: 'darkweb',
    schema: DARKWEB_SCHEMA,
    systemPrompt: DARKWEB_SYSTEM_PROMPT,
    userPrompt: 'Research recently reported dark web / underground forum activity.',
    sanitize: sanitizeDarkwebItem,
    stableId: stableDarkwebId,
    globalVar: 'TIP_AUTOFEED_DARKWEB',
    fileName: 'autofeed-darkweb.js',
  },
];

// Runs one content type end-to-end: Claude + web_search -> sanitize -> stamp id/fetchedAt.
export async function runContentType(client, type) {
  const { items } = await fetchContent(client, {
    label: type.label,
    schema: type.schema,
    systemPrompt: type.systemPrompt,
    userPrompt: type.userPrompt,
  });
  const sanitized = items.map(type.sanitize).filter(Boolean);
  if (sanitized.length < items.length) {
    console.warn(`[${type.label}] dropped ${items.length - sanitized.length} item(s) that failed validation.`);
  }
  const now = new Date().toISOString();
  return sanitized.map((item) => ({ id: type.stableId(item), ...item, fetchedAt: now }));
}

export function renderAutofeedFile(type, records) {
  return `/* ═══════════════════════════════════════════════════════════════════
   Auto-generated by the TIP fetch-intel pipeline on a 6-hour schedule.
   Do not hand-edit — changes are overwritten on the next run.
   Content type: ${type.key}
   Last run: ${new Date().toISOString()}
   ═══════════════════════════════════════════════════════════════════ */
const ${type.globalVar} = ${JSON.stringify(records, null, 2)};
`;
}
